version: '3'

services:
  api:
    container_name: upgames_api
    image: wongames/api:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: wongames
      DATABASE_PASSWORD: wongames123
      DATABASE_NAME: wongames
      STRIPE_KEY: 'pk_test_51Gr9kdH501LastbVjfwawl3E1csHMdEiPEeSBMdAzAS1egsBRaEUQpE78p3EIfS150ckSO5Rnl0F2DCYD9PpHFHq00RgGA8m7p'
    ports:
      - '1337:1337'
    depends_on:
      - db
  db:
    container_name: upgames_db
    image: wongames/database:latest
    ports:
      - '5432:5432'
